@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}


### CREATE ONE
POST {{host}}/customers
Accept: application/json
Content-Type: application/json

{
  "CompanyName": "bonjour"
}

### READ ALL
GET {{host}}/customers
Accept: application/json

### READ ONE
GET {{host}}/customers/1
Accept: application/json

### DELETE ALL
DELETE {{host}}/customers/
Accept: application/json

### DELETE ONE
DELETE {{host}}/customers/12
Accept: application/json