@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}


### CREATE ONE
POST {{host}}/customers
Accept: application/json
Content-Type: application/json

{
  "CompanyName": "bonkur"
}

### CREATE ONE WHERE
POST {{host}}/customers
Accept: application/json
Content-Type: application/json

{
  "CompanyName": "bonkur",
  "Country": "URL",
  "City": "FuckYou"
}

### READ ALL
GET {{host}}/customers
Accept: application/json

### READ ALL Tricked
GET {{host}}/customers
Accept: application/json/cndtn

### READ WHERE
GET {{host}}/customers/cndtn?Country=URL&City=FuckYou
Accept: application/json

### READ ONE
GET {{host}}/customers/1
Accept: application/json

### DELETE ALL
DELETE {{host}}/customers/
Accept: application/json

### DELETE ALL Tricked
DELETE {{host}}/customers/cndtn
Accept: application/json

### DELETE WHERE
DELETE {{host}}/customers/cndtn?Country=URL&City=FuckYou
Accept: application/json

### DELETE ONE
DELETE {{host}}/customers/23
Accept: application/json