@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}


### CREATE ONE
POST {{host}}/products
Accept: application/json
Content-Type: application/json

{
  "ProductName": "potato3",
  "Discontinued": false
}

### READ ALL
GET {{host}}/products
Accept: application/json

### READ ONE
GET {{host}}/products/2
Accept: application/json

### DELETE ALL // TODO fix
DELETE {{host}}/products/
Accept: application/json

### DELETE ONE // TODO return deleted elem
DELETE {{host}}/products/7
Accept: application/json